### ISSUE TITLE
Searching Only Existing Locally fails

### ISSUE THREAD

**Issue by matt454357** [brenkmanco/hackpdm#10]
Received an error message when search for "Only Existing Locally"

> Data Error:
> Failed updating search results list.
> ERROR: 54001: stack depth limit exceeded

![image](https://cloud.githubusercontent.com/assets/7604932/7712194/fcf5eff2-fe2c-11e4-9b3b-db43f32f6ed5.png)

**Comment by briggsj3** [comment]
Please verify that this issue has been resolved with commit a131958 (my latest).

**Comment by matt454357** [comment]
Still getting the same error.  I checked the query string you are sending to the server, and it contains over 1 million characters.  That may have something to do with it.  I have over 7,800 files in my local working copy.  Here's a sample of the query that gets sent to the server:

``` sql
SELECT * FROM (
    SELECT
        '/Catalog/design library/annotations' AS rel_path,
        '0.25 fillet both side.sldweldfvt' AS entry_name
    UNION SELECT
        '/Catalog/design library/annotations' AS rel_path,
        'blend weld.sldweldfvt' AS entry_name
    UNION SELECT
        '/Catalog/design library/annotations' AS rel_path,
        'composite position.sldgtolfvt' AS entry_name
.
.
.
    UNION SELECT
        '/Sandbox/Tier IV/T4f Engine/Electrical' AS rel_path,
        'c-4-1418390-1-j-3d DOC TEMP PLUG.SLDPRT' AS entry_name
) AS l
LEFT JOIN view_dir_tree AS t ON t.dir_name=l.rel_path
LEFT JOIN hp_entry AS e ON l.entry_name=e.entry_name
WHERE e.entry_id IS NULL
LIMIT 100;
```

**Comment by matt454357** [comment]
I tried executing the query from pgadmin, and got this error:

> ERROR:  stack depth limit exceeded
> HINT:  Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.

From the postgresql docs:

> VALUES lists with very large numbers of rows should be avoided, as you may encounter out-of-memory failures or poor performance. VALUES appearing within INSERT is a special case (because the desired column types are known from the INSERT's target table, and need not be inferred by scanning the VALUES list), so it can handle larger lists than are practical in other contexts.

So, which approach to use for the solution, here?
1. Pull a list of all files from the server, and compare locally
2. Create a temporary table, push the local file list to it, and compare on the server

I expect that pushing to the server will give better performance, overall, so I think we should try the temp table (solution 2).

**Comment by matt454357** [comment]
Actually, there are other solutions:
1. Pull a list of all entries from the server, and compare locally
2. Create a temporary table, push the local file list to it, and compare on the server
3. Prepare a statement and execute it once for every local file
4. First identify local only directories and show the contained files, then retrieve server entries for only the remote directories that exist locally and compare against those (similar to 1, but more efficient/complex)

We need to think about which of these approaches will work best when we switch to Odoo for the backend.  Option 3 would be easiest, but would probably have the worst performance.  I think we could implement something like option 2 for Odoo.  I'm going to implement option 2.
